from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_line', models.CharField(choices=[('sgpt', 'SGPT'), ('functional', 'Functional'), ('treatments', 'Treatments'), ('retail', 'Retail')], max_length=30)),
                ('kind', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('category', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, max_length=60)),
                ('vat_included', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, max_length=240)),
                ('attachment_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('stage', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('booked_consultation', 'Booked Consultation'), ('attended', 'Attended'), ('trial_started', 'Trial Started'), ('converted', 'Converted'), ('active_member', 'Active Member'), ('at_risk', 'At Risk'), ('churned', 'Churned')], default='new', max_length=30)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('campaign', models.CharField(blank=True, max_length=120)),
                ('adset', models.CharField(blank=True, max_length=120)),
                ('ad', models.CharField(blank=True, max_length=120)),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=120)),
                ('click_id', models.CharField(blank=True, max_length=180)),
                ('expected_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('probability', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LeadIntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='generic', max_length=60)),
                ('raw_payload', models.JSONField(default=dict)),
                ('mapped_email', models.EmailField(blank=True, max_length=254)),
                ('mapped_phone', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly')], max_length=20)),
                ('included_credits', models.PositiveIntegerField(blank=True, null=True)),
                ('unlimited_classes', models.BooleanField(default=False)),
                ('freeze_rules', models.TextField(blank=True)),
                ('cancellation_terms', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineConversionConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=40)),
                ('enabled', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='OverheadConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('per_active_member', 'Per Active Member'), ('revenue_share', 'Revenue Share')], default='per_active_member', max_length=30)),
                ('monthly_overhead', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('coach', 'Coach'), ('reception', 'Reception'), ('member', 'Member'), ('practitioner', 'Practitioner')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_type', models.CharField(choices=[('sgpt', 'SGPT'), ('functional', 'Functional Fitness'), ('treatment', 'Treatment')], max_length=20)),
                ('room', models.CharField(choices=[('sgpt_room', 'SGPT Room'), ('functional_room', 'Functional Room'), ('treatment_room', 'Treatment Room')], max_length=30)),
                ('title', models.CharField(max_length=120)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('recurrence_rule', models.CharField(blank=True, max_length=120)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaching_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week', models.PositiveIntegerField(default=1)),
                ('day', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=120)),
                ('content', models.JSONField(default=dict)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='gymapp.program')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('consent_checked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_bookings', to=settings.AUTH_USER_MODEL)),
                ('practitioner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioner_bookings', to=settings.AUTH_USER_MODEL)),
                ('treatment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gymapp.treatmenttype')),
            ],
        ),
        migrations.CreateModel(
            name='PackageAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.productaddon')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='gymapp.membershippackage')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gymapp.membershippackage')),
            ],
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waiver_signed', models.BooleanField(default=False)),
                ('parq_flag', models.BooleanField(default=False)),
                ('emergency_contact', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='gymapp.lead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(max_length=40)),
                ('content', models.TextField(blank=True)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='gymapp.lead')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionalWOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workout', models.JSONField(default=dict)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='functional_wod', to='gymapp.session')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectorRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='stubbed', max_length=20)),
                ('response', models.JSONField(default=dict)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='gymapp.offlineconversionconnector')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('waitlist', 'Waitlist'), ('canceled', 'Canceled'), ('checked_in', 'Checked In')], default='booked', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='gymapp.session')),
            ],
            options={'unique_together': {('member', 'session')}},
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.CharField(max_length=120)),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('load', models.FloatField(default=0)),
                ('rpe', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='gymapp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout_instance', to='gymapp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='ConversionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=60)),
                ('metadata', models.JSONField(default=dict)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymapp.booking')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymapp.lead')),
            ],
        ),
    ]
